name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: UI

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run UI Tests
        uses: "vgaidarji/android-github-actions/emulator@v1.0.0"
