name: Testing  Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  push:
    branches:
      - master

jobs:
  testing:
    name: UI

    runs-on: ubuntu-18.04

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

     

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run UI Tests
        uses: vgaidarji/android-github-actions-emulator@v1.0.0
